
on:
  push: 
    branches: main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        $cloudInitRaw = Get-Content ./arm/cloud-config.yml -raw
        $cloudInit64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($cloudInitRaw))
        Get-Content ./arm/parameters.json | % {
          $_ -replace '{{KeyVaultId}}', '${{ secrets.KEYVAULT_REFERENCEID }}' -replace '{{cloud-init}}', $cloudInit64
        } | Set-Content ./arm/parameters.json
      shell: pwsh
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-minecraft
        template: ./arm/template.json
        parameters: ./arm/parameters.json
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
