
on:
  push: 
    branches: main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: Get-Content ./arm/parameters.json | % { $_ -replace '{{KeyVaultId}}', '${{ secrets.KEYVAULT_REFERENCEID }}' } | Set-Content ./arm/parameters.json
      shell: pwsh
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-minecraft
        template: ./arm/template.json
        parameters: ./arm/parameters.json
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
